### ISSUE TITLE
Error in { : task 14 failed - "invalid 'length' argument"

### ISSUE THREAD

**Issue by ahwanpandey** [darneson/MethylResolver#5]
Hello,

I am getting this error with my data.

```
> res = MethylResolver(methylMix = beta_vals, betaPrime = FALSE, doPar = TRUE, numCores = 6, absolute = FALSE)
Beginning LTS Deconvolution For This Mixture...
  |=====================================================================================================================================| 100%
Error in { : task 14 failed - "invalid 'length' argument"
```

Please help.

Thanks,
Ahwan

**Comment by ahwanpandey** [comment]
Different subsets/combinations of the data works but not when I put the whole dataset. 

```
> res = MethylResolver(methylMix = beta_vals[,50:80,drop=FALSE], betaPrime = FALSE, doPar = TRUE, numCores = 6, absolute = TRUE)
Beginning LTS Deconvolution For This Mixture...
  |=====================================================================================================================================| 100%
Error in { : task 4 failed - "invalid 'length' argument"
In addition: There were 12 warnings (use warnings() to see them)

> res = MethylResolver(methylMix = beta_vals[,60:80,drop=FALSE], betaPrime = FALSE, doPar = TRUE, numCores = 6, absolute = TRUE)
Beginning LTS Deconvolution For This Mixture...
  |=====================================================================================================================================| 100%
Completed LTS Deconvolution For This Mixture...
```

**Comment by darneson** [comment]
Hello,

Is it possible to share your beta_vals matrix with me? It is a bit
difficult to debug without seeing the data. Can you post a reproducible
example?

Best,
Doug

**Comment by ahwanpandey** [comment]
Hi Doug,

Thanks for your reply. This is unpublished data so I am a bit hesitant to do that just yet.

Since different subsets work, should I just run with a batch of 20 or 30 at a time? Would the end result be the same/similar if I ran all 126 together?

Thanks,
Ahwan

**Comment by darneson** [comment]
Hi Ahwan,

I completely understand, however, it is a bit difficult on my end to debug
the issue without a reproducible example.

The workaround that you propose will work as intended (each sample is
considered independently for the deconvolution). The results should be
exactly the same if you pass multiple subsets of your ample versus all
samples at the same time.

Best,
Doug

**Comment by ahwanpandey** [comment]
Great thanks for that.
